# This is a config for E2B sandbox template.
# You can use template ID (ybdni0ui0l3vsumat82v) or template name (nova-ocr-simple) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nova-ocr-simple") # Sync sandbox
# sandbox = await AsyncSandbox.create("nova-ocr-simple") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nova-ocr-simple')

team_id = "608eb540-d17b-4420-b632-6514e50a105d"
memory_mb = 2_048
cpu_count = 2
dockerfile = "e2b-simple.Dockerfile"
template_name = "nova-ocr-simple"
template_id = "ybdni0ui0l3vsumat82v"
