# This is a config for E2B sandbox template.
# You can use template ID (ybdni0ui0l3vsumat82v) or template name (nova-engine-v3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nova-engine-v3") # Sync sandbox
# sandbox = await AsyncSandbox.create("nova-engine-v3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nova-engine-v3')

team_id = "608eb540-d17b-4420-b632-6514e50a105d"
memory_mb = 2_048
cpu_count = 2
dockerfile = "e2b-v4-multiformat.Dockerfile"
template_name = "nova-engine-v4"
template_id = "jv6tng9kik3nom340nx0"
